# Generated by Django 6.0.2 on 2026-03-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VaccumBags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supermarket', models.CharField(max_length=200)),
                ('bag', models.CharField(max_length=200)),
                ('size', models.IntegerField(default=0)),
            ],
        ),
    ]
