# Generated by Django 6.0.2 on 2026-03-02 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bagsearch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccumbags',
            old_name='bag',
            new_name='vacuum',
        ),
    ]
