# Generated by Django 6.0.2 on 2026-03-02 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bagsearch', '0002_rename_bag_vaccumbags_vacuum'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VaccumBags',
            new_name='VacumBags',
        ),
    ]
