# Generated by Django 6.0.2 on 2026-03-02 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bagsearch', '0003_rename_vaccumbags_vacumbags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VacumBags',
            new_name='VacuumBags',
        ),
    ]
