# Generated by Django 6.0.2 on 2026-03-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagsearch', '0004_rename_vacumbags_vacuumbags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacuumbags',
            name='size',
            field=models.CharField(max_length=200),
        ),
    ]
